name        : patch
version     : 2.7.5
release     : 3
source      :
    - ftp://ftp.gnu.org/gnu/patch/patch-2.7.5.tar.xz : fd95153655d6b95567e623843a0e77b81612d502ecf78a489a4aed7867caa299
homepage    : http://savannah.gnu.org/projects/patch
license     :
    - GPL-3.0
summary     : patch (patches source files)
description : |
    patch takes other "patch" files created between an original and changed version and applies them to original files, producing a changed version.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
