name       : patch
version    : 2.7.6
release    : 8
source     :
    - ftp://ftp.gnu.org/gnu/patch/patch-2.7.6.tar.xz : ac610bda97abe0d9f6b7c963255a11dcb196c25e337c61f94e4778d632f1d8fd
homepage   : https://savannah.gnu.org/projects/patch
license    : GPL-3.0-or-later
component  : system.devel
summary    : patch (patches source files)
description: |
    patch takes other "patch" files created between an original and changed version and applies them to original files, producing a changed version.
builddeps  :
    - attr-devel
setup      : |
    %apply_patches
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
